#!/bin/bash

# Readline library configuration options
# http://ss64.com/bash/syntax-inputrc.html

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Disable beeping and window flashing
set bell-style none

# Use case-insensitive TAB autocompletion
set completion-ignore-case on

# Auto list TAB completions
set show-all-if-ambiguous off


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Mappings for Ctrl-left-arrow and Ctrl-right-arrow for word moving

"\e[1;5C": forward-word
"\e[1;5D": backward-word
"\e[5C": forward-word
"\e[5D": backward-word
"\e\e[C": forward-word
"\e\e[D": backward-word
