[ids]
*

[main]
leftcontrol = leftmeta
leftmeta = leftalt
leftalt = leftcontrol

rightcontrol = rightmeta
rightmeta = rightalt
rightalt = rightcontrol
# Print Screen key on thinkpad keyboards
sysrq = rightalt


# --- THE NAVIGATION LAYER ---
# Caps Lock: Tap for Esc, Hold for Nav Layer
capslock = layer(nav_layer)

[nav_layer]
# Basic IJKL Arrows
i = up
k = down
j = left
l = right

# Other Nav Keys
p = delete
o = pageup
u = pagedown
m = enter
h = home
; = end
f = tab
e = esc
n = =
space = backspace
