# Performance settings
backend = "glx";
vsync = true;
use-damage = true;  # Only redraw parts of the screen that changed

# This makes inactive windows slightly see-through so you can keep an eye on background tasks.
inactive-opacity = 0.85;
frame-opacity = 0.7;
inactive-opacity-override = false;

# Use this to keep specific apps (like video players) 100% opaque
opacity-rule = [
    "100:class_g = 'mpv'",
    "100:class_g = 'Firefox'"
];


# Fading & shadows
fading = true;
fade-delta = 4;        # Speed of the fade (lower is faster)
fade-in-step = 0.03;
fade-out-step = 0.03;

shadow = true;
shadow-radius = 7;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-exclude = [ "class_g = 'i3-frame'" ]; # Prevents double shadows on i3 gaps

shadow-exclude = [
  "name = 'Notification'",
  "class_g = 'Conky'",
  "class_g ?= 'Notify-osd'",
  "class_g = 'Cairo-clock'",
  "_GTK_FRAME_EXTENTS@:c",
  "class_g = 'Polybar'"
];